### ISSUE TITLE
[BUG] Witch Hunters outside the Empire go crazy

### ISSUE THREAD

**Issue by HobbitDerrick** [Hexenstag-Team/WH-Hexenstag-Dev#41]
The event witchhunter.8 leads to accusations of any character who doesn't match the culture group of the Witch Hunter. Hunters are always Imperial group, so when they're operating in Tilea they accuse a random local each time witchhunter.8 fires from its 3 month MTTH. It's kind of great if you're playing a MR because the Hunters murder multiple patricians each year and let you inherit their wealth, but not great storytelling. (I'm reporting this as a bug rather than doing a quick fix because I understand that there's an Empire overhaul cooking.)
![suspicioustileansintilea](https://user-images.githubusercontent.com/85831100/121879507-0f785c00-cd61-11eb-858d-98d118c7e4f2.JPG)

**Comment by Hexenstag** [comment]
What a madlad.
