### ISSUE TITLE
Add a submod to remove needed DLCs?

### ISSUE THREAD

**Issue by gmb360** [Hexenstag-Team/WH-Hexenstag-Dev#63]
I know you all use the charlemagne Unit Models to create the Greenskins Army models (they look amazing btw) but it would perhaps be good to simply add a Submod that Removes this custom Model so that people without the DLC may enjoy the Mod aswell

**Comment by Hexenstag** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2592169248
